version: "3"

services:

    db:
        image: "postgres:latest"
        container_name: "hofv-postgres"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "54320:5432"
        volumes:
            - "pgdata:/var/lib/postgresql/data"


volumes:
    pgdata:
