# Generated by Django 3.0.7 on 2020-07-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='title',
            new_name='name',
        ),
    ]
