# Generated by Django 3.0.7 on 2020-07-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_auto_20200720_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='name',
            new_name='title',
        ),
    ]
